name: "GitHubAutoUpdater CLI"
description: "Publishes a new release via GitHubAutoUpdater CLI"
author: "Krzysztof"

inputs:
  version:
    description: 'Version to publish'
    required: true
  app:
    description: 'Path to the app executable to publish'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build GitHubUpdater CLI
      shell: pwsh
      run: dotnet publish src/GitHubAutoUpdater.Cli/GitHubAutoUpdater.Cli.csproj -c Release -r win-x64 --self-contained true

    - name: Run GitHubUpdater CLI
      shell: pwsh
      run: |
        .\src\GitHubAutoUpdater.Cli\bin\Release\net9.0\win-x64\githubautoupdater.exe publish --version ${{ inputs.version }} --app ${{ inputs.app }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}